### ISSUE TITLE
Problem with version 1.6.6

### ISSUE THREAD

**Issue by francocv6** [d2cml-ai/HDMJL.jl#13]
There is a problem using the package with version 1.6.6 of julia.
![image](https://user-images.githubusercontent.com/89536356/192627112-3abce1ee-772e-4e1f-b48d-00c23cc4ffe0.png)
This is the error that is shown when I want to use the package. 
It would be great you could check that @RodrigoGrijalba .

**Comment by RodrigoGrijalba** [comment]
That's my bad. I forgot to remove the compatibility with 1.6 when I added the broadcasted short-circuit evaluators back to the treatment effect functions. A fix should be published in a few minutes.

**Comment by RodrigoGrijalba** [comment]
Fix should be out now. Try reinstalling the package.
